### ISSUE TITLE
is there supposed to be an audible response?

### ISSUE THREAD

**Issue by SandiaScalpel** [createcandle/voco#8] opened 2020-02-26 04:19 UTC
Hi I believe I have successfully installed web things gateway onto a raspberry pi 3 vB

 I have installed this add-on with a Playstation eye and a mini spreadsheet plugged in to the audio jack of the Pi, and in general it works. I do not understand what is supposed to happen, though, when I say "hey snips, what time is it?" Whenever I say "hey snips ....," the mini speaks emits a rising tone but nothing else. Is the mini-speaker supposed to tell me the time audibly?

Maybe I have something configured wrong?

Sean

**Comment by TobiBu** [comment] 2020-05-06 19:32
Hi,

I have a similar issue. The log files for me state an Error message which reads like this:

> 2020-05-06 21:27:36.592 ERROR  : voco: INFO:snips_asr_hermes::handler : Publishing the recognition

2020-05-06 21:27:36.593 ERROR  : voco: INFO:snips_asr_hermes::handler : Preparing decoder
2020-05-06 21:27:36.673 ERROR  : voco: Using Lingware directory: /home/pi/.mozilla-iot/addons/voco/snips/lang
2020-05-06 21:27:36.677 ERROR  : voco: error: opening pcm device failed No such file or directory
2020-05-06 21:27:36.679 ERROR  : voco: nanotts: pcm.c:736: snd_pcm_stream: Assertion `pcm' failed.
2020-05-06 21:27:36.682 ERROR  : voco: INFO:snips_dialogue_lib::coordinator::coordinator: Session [4c1593f2-52fa-4589-a059-e52b1e7d5e0f]: closing session which was active: Nominal
2020-05-06 21:27:36.683 ERROR  : voco: INFO:snips_dialogue_lib::coordinator::coordinator: Site [default]: reset site -> turn off ASR and turn on Hotword
2020-05-06 21:27:36.724 ERROR  : voco: INFO:snips_hotword_lib::audio    : Audio thread for site default started.

Maybe this helps the developers to find the error...

**Comment by flatsiedatsie** [comment] 2020-05-22 17:58
Are you running this on a Raspberry Pi or something else?

**Comment by TobiBu** [comment] 2020-05-22 18:43
Yes, on the raspberry pi 4.

**Comment by flatsiedatsie** [comment] 2020-05-22 18:48
And are you using the official WebThings Pi image?

**Comment by TobiBu** [comment] 2020-05-22 18:55
Yes, I do.

**Comment by flatsiedatsie** [comment] 2020-05-23 11:30
I did a test with a clean Gateway image, and everything seems to work ok.

- First boot. I created a something.mozila-iot.org link.
- Install Voco add-on.
- Create authorization code
- Add authorization code to Voco settings, and enabled debug output.
- Restarted the device so I could connect a better microphone.

Everything works ok.

Here is what I am seeing in the debug log:
```
2020-05-23 11:44:07.547 INFO   : voco: numid=3,iface=MIXER,name='PCM Playback Route'
2020-05-23 11:44:07.548 INFO   : voco:   ; type=INTEGER,access=rw------,values=1,min=0,max=3,step=0
2020-05-23 11:44:07.549 INFO   : voco:   : values=1
2020-05-23 11:44:08.719 ERROR  : voco: INFO:snips_tts_hermes: starting with provider CustomTts { command: ["/home/pi/.mozilla-iot/addons/voco/snips/speak.sh", "%%TEXT%%"] }
2020-05-23 11:44:08.767 INFO   : voco: Voco thing created
2020-05-23 11:44:08.768 INFO   : voco: Setting status on thing to: Checking...
2020-05-23 11:44:08.769 INFO   : voco: set_value called for feedback-sounds
2020-05-23 11:44:08.770 INFO   : voco: User wants to switch feedback sounds to: True
2020-05-23 11:44:08.771 INFO   : voco: Saving to persistence data store at path: /home/pi/.mozilla-iot/data/voco/persistence.json
2020-05-23 11:44:08.771 INFO   : voco: Persistence file existed. Will try to save to it.
2020-05-23 11:44:08.772 INFO   : voco: property -> update
2020-05-23 11:44:08.772 INFO   : voco: Updated voco thing
2020-05-23 11:44:08.773 INFO   : voco: available audio cards: ['ALSA', 'Device']
2020-05-23 11:44:08.774 INFO   : voco: Possible audio playback devices: ['Built-in headphone jack (0,0)', 'Built-in HDMI (0,1)']
2020-05-23 11:44:08.774 INFO   : voco: Possible audio capture devices: ['Attached device (1,0)']
```

I did see this on the first run:

```
2020-05-23 11:42:28.132 INFO   : voco: Could not load persistent data (if you just installed the add-on then this is normal)
2020-05-23 11:42:28.132 INFO   : voco: Error: could not make sure work dir exists
````
But I think that just has to do with it being the first run. I has a look at the code, and it is a bit odd. It's the temporary directory NanoTTS uses to output speech.


```
2020-05-23 11:43:02.667 ERROR  : voco: error: snd_pcm_writei: Broken pipe
2020-05-23 11:43:02.668 ERROR  : voco: ALSA lib pcm.c:8424:(snd_pcm_recover) underrun occurred
```
But if I remember correctly that's normal.


From your log it seems to be an issue with NanoTTS, the text to speech application that Voco uses to output speech. But I'm not sure why it wouldn't work.

Are you using the 3,5mm output jack for audio output, or a USB speaker? Is there anything out of the ordinary about your setup?

**Comment by TobiBu** [comment] 2020-05-26 19:00
Hi,

thanks for the detailed answer. I could try using a fresh install and flash a new SD card.

I am using the 3.5mm output jack and have nothing special in my setup.

**Comment by TobiBu** [comment] 2020-06-07 16:29
Hi,

I made some more checks and found in the debug output of voco the following lines:

> 2020-06-07 18:23:35.415 INFO   : voco: Error speaking: Command '('/home/pi/.mozilla-iot/addons/voco/snips/nanotts', '-l', '/home/pi/.mozilla-iot/addons/voco/snips/lang', '-v', 'en-GB', '--speed', '0.9', '--pitch', '1.2', '-p')' died with <Signals.SIGABRT: 6>.

> 2020-06-07 18:23:35.463 ERROR  : voco: Using Lingware directory: /home/pi/.mozilla-iot/addons/voco/snips/lang
2020-06-07 18:23:35.465 ERROR  : voco: error: opening pcm device failed No such file or directory
2020-06-07 18:23:35.466 ERROR  : voco: nanotts: pcm.c:736: snd_pcm_stream: Assertion `pcm' failed.
2020-06-07 18:23:35.467 ERROR  : voco: INFO:snips_dialogue_lib::coordinator::coordinator: Session [9d8682e7-9220-4ec0-abb1-913d12bd4679]: closing session which was active: Nominal
2020-06-07 18:23:35.467 ERROR  : voco: INFO:snips_dialogue_lib::coordinator::coordinator: Site [default]: reset site -> turn off ASR and turn on Hotword
2020-06-07 18:23:35.513 ERROR  : voco: INFO:snips_hotword_lib::audio    : Audio thread for site default started.

Not sure what those lines mean but there is definitely something broken. If I find the time I will try again with a fresh install of the gateway.

**Comment by flatsiedatsie** [comment] 2020-06-08 14:58
yes, it seems the text-to-speech program is crashing because it cannot find the [PCM interface](https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html). Very odd.

**Comment by createcandle** [comment] 2020-06-09 18:32
I just had the opposite experience, where a ReSpeaker output worked, and the 'bleep' noises could not be heard. Mostly likely because they are being played over the built-in 3,5" headphone jack.

@SandiaScalpel In the Voco settings, have you made sure that the audio output it set to the built in headphone jack?

**Comment by LionMike** [comment] 2020-06-10 02:54
I am experiencing this issue also.

**Comment by createcandle** [comment] 2020-06-11 10:52
I am wondering if the sound is perhaps sent over the HDMI output.

Just to make sure: in the Voco settings (settings -> addons -> Voco -> settings), is the audio output set to the desired channel, e.g. the 3.5mm headphone jack?

What happens if you log in via SSH, and use`sudo raspi-config` to force audio output over the audio jack instead of HDMI?

If you log-in via SSH, then you could also try `speaker-test -c2` to test if the speakers can make sound. Or you can install the `internet-radio` addon to test this.

if you run `aplay -l` you should see all your audio output options. This is what the Voco addon uses internally to offer the various options on the settings page. In my case I see this on a Pi 4:

```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
(One analog output called "card 0, device 0", and 2 HDMI ports).

**Comment by createcandle** [comment] 2020-07-08 19:56
A  new version has been created that should hopefully solve your issue. It should hopefully be accepted soon.

**Comment by LionMike** [comment] 2020-07-08 21:31
Cool. It's working well for me but I'm having a little difficulty
understanding Snips accent. Lol. Just wondering what country she is from.
Also is there a way to view reply in the log file?

**Comment by createcandle** [comment] 2020-07-09 08:45
Yes, if you enable the 'debug' setting of Voco you can see everything that happens, including how Snips interprets your query.

It's theoretically possible to change the accent (currently set to British), as well as the pitch and speed of the voice replies. It could become a feature in the future.

**Comment by LionMike** [comment] 2020-07-09 12:53
I performed the update and lost audio output. Output is set to auto. Here is the log file.
2020-07-09 07:49:07.929 INFO   : voco: self.audio_output_options = ['Built-in headphone jack', 'Built-in video', 'Built-in video1', 'USB Audio']
2020-07-09 07:49:07.930 INFO   : voco: adding audio output property with list: ['Built-in headphone jack', 'Built-in video', 'Built-in video1', 'USB Audio']
2020-07-09 07:49:07.931 INFO   : voco: **error adding properties: 'audio_output'**
2020-07-09 07:49:07.933 INFO   : voco: Voco thing has been created
2020-07-09 07:49:07.937 INFO   : voco: Voco thing created
2020-07-09 07:49:07.939 INFO   : voco: Setting status on thing to: Checking...
2020-07-09 07:49:07.940 INFO   : voco: property -> update. Value = Checking...
2020-07-09 07:49:07.942 INFO   : voco: new value
2020-07-09 07:49:07.943 INFO   : voco: Updated voco thing
2020-07-09 07:49:07.945 INFO   : voco: available audio cards: ['ALSA', 'Connect']
2020-07-09 07:49:07.946 INFO   : voco: Possible audio capture devices: ['Attached device (1,0)']
2020-07-09 07:49:07.948 INFO   : voco: Snips has already been extracted
2020-07-09 07:49:07.951 INFO   : voco: -Debugging was in config
2020-07-09 07:49:07.953 INFO   : voco: Debugging enabled
2020-07-09 07:49:07.959 INFO   : voco: -Microphone is present in the config data: Attached device (1,0)
2020-07-09 07:49:07.961 INFO   : voco: --Using microphone from config
2020-07-09 07:49:07.967 INFO   : voco: -Speaker is present in the config data: Auto
2020-07-09 07:49:07.970 INFO   : voco: -Metric preference is present in the config data.
2020-07-09 07:49:07.971 INFO   : voco: -Authorization token is present in the config data.
2020-07-09 07:49:07.973 INFO   : voco: GET PATH = /things
2020-07-09 07:49:07.975 INFO   : voco: API GET: 200, OK
2020-07-09 07:49:07.977 INFO   : voco: self.server is now: http://127.0.0.1:8080
2020-07-09 07:49:07.982 INFO   : voco: Setting audio input to USB/Hat
2020-07-09 07:49:07.983 INFO   : voco: Setting audio output to automatically switch
2020-07-09 07:49:07.986 ERROR  : voco: Traceback (most recent call last):
2020-07-09 07:49:07.987 ERROR  : voco:   File "/home/pi/.mozilla-iot/addons/voco/main.py", line 40, in <module>
2020-07-09 07:49:07.988 ERROR  : voco:     _ADAPTER = VocoAdapter(verbose=False)
2020-07-09 07:49:07.990 ERROR  : voco:   File "/home/pi/.mozilla-iot/addons/voco/pkg/voco_adapter.py", line 404, in __init__
2020-07-09 07:49:07.992 ERROR  : voco:     if option['human_device_name'] == str(self.persistent_data['audio_output']):
2020-07-09 07:49:07.993 ERROR  : voco: KeyError: 'audio_output'
2020-07-09 07:49:08.193 INFO   : Plugin: voco died, code = 1 restarting after 3000

**Comment by createcandle** [comment] 2020-07-09 20:05
Thanks for sharing this, I'm fixing it now. The problem is that the new values aren't in your persistent data. You could try to reinstall Voco, or manually remove the file `./mozilla/data/voco/persistence.json`.

**Comment by LionMike** [comment] 2020-07-09 20:32
By reinstall do you mean remove from add-ons then reinstall, or clone from repository?

**Comment by createcandle** [comment] 2020-07-09 21:02
I meant remove from addons, but I'm not sure if that actually removes the persistence file. 

In any case, the new version has just been [accepted by Mozilla](https://github.com/mozilla-iot/addon-list/pull/912), so you should have it on your device soon.

**Comment by createcandle** [comment] 2020-07-14 06:40
Has the issue been fixed?

**Comment by LionMike** [comment] 2020-07-14 23:23
It is working. However I can only get output through the headphone jack of the microphone. Even if I set all output settings to headphone jack. Currently it is set to built in headphone jack. Also the update failed and it took several attempts to remove and reinstall. After removing from add-ons it was still showing on the dashboard so I had to remove it there. Internet radio no longer worked so I removed that and haven't reinstalled it yet.

**Comment by flatsiedatsie** [comment] 2020-07-16 17:06
Just to be certain: you do realise that the audio settings are now on the 'thing' instead of in the Voco settings?

The Internet Radio addon has alos moved to this 'select audio output on the thing instead of settings' model. It allows you to quickly change where audio it sent to. Voco and Internet Radio should now no longer interfere with each other.

**Comment by LionMike** [comment] 2020-07-16 17:39
I did notice that and currently have it set for Built-in headphone jack with audio still not coming through the jack on the Pi. Incidentally I am using Pi3B. I will reinstall internet radio and check settings. Thank you for your help.

**Comment by flatsiedatsie** [comment] 2020-07-20 14:02
And have you gone into setting and 'forced' the output to the headphone jack?

**Comment by LionMike** [comment] 2020-07-20 15:16
Yes I did. What I will get is the feedback sounds out of the headphone jack, but the voice still comes through the headphone output of the Samson mic. I've yet to try it with a different mic.

**Comment by flatsiedatsie** [comment] 2020-07-20 17:10
So the feedback sounds come out ok, but the voice does not? That's.. incredible.

Could you enable the debugging option of Voco? After you hit save, have a look at the internal logs, and could you share what Voco reports there as the audio devices it found?

It should look something like:

```
voco: [{'card_id': 0, 'device_id': 0, 'simple_card_name': 'ALSA', 'full_card_name': 'bcm2835 ALSA', 'full_device_name': 'bcm2835 ALSA', 'human_device_name': 'Built-in headphone jack', 'control_name': 'PCM', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}, {'card_id': 0, 'device_id': 1, 'simple_card_name': 'ALSA', 'full_card_name': 'bcm2835 ALSA', 'full_device_name': 'bcm2835 IEC958/HDMI', 'human_device_name': 'Built-in video', 'control_name': 'PCM', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}, {'card_id': 0, 'device_id': 2, 'simple_card_name': 'ALSA', 'full_card_name': 'bcm2835 ALSA', 'full_device_name': 'bcm2835 IEC958/HDMI1', 'human_device_name': 'Built-in video1', 'control_name': 'PCM', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}]
```

**Comment by LionMike** [comment] 2020-07-20 18:15
Here are some log details:
 voco: [{'card_id': 0, 'device_id': 0, 'simple_card_name': 'ALSA', 'full_card_name': 'bcm2835 ALSA', 'full_device_name': 'bcm2835 ALSA', 'human_device_name': 'Built-in headphone jack', 'control_name': 'PCM', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}, {'card_id': 0, 'device_id': 1, 'simple_card_name': 'ALSA', 'full_card_name': 'bcm2835 ALSA', 'full_device_name': 'bcm2835 IEC958/HDMI', 'human_device_name': 'Built-in video', 'control_name': 'PCM', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}, {'card_id': 0, 'device_id': 2, 'simple_card_name': 'ALSA', 'full_card_name': 'bcm2835 ALSA', 'full_device_name': 'bcm2835 IEC958/HDMI1', 'human_device_name': 'Built-in video1', 'control_name': 'PCM', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}, {'card_id': 1, 'device_id': 0, 'simple_card_name': 'Connect', 'full_card_name': 'Samson Go Mic Connect', 'full_device_name': 'USB Audio', 'human_device_name': 'USB Audio', 'control_name': 'Speaker', 'complex_control_id': None, 'complex_count': None, 'complex_max': None}]

**Comment by LionMike** [comment] 2020-07-20 18:19
More log info:
 INFO   : voco: self.audio_output_options = ['Built-in headphone jack', 'Built-in video', 'Built-in video1', 'USB Audio']
2020-07-19 07:23:05.296 INFO   : voco: adding audio output property with list: ['Built-in headphone jack', 'Built-in video', 'Built-in video1', 'USB Audio']
2020-07-19 07:23:05.300 INFO   : voco: Voco thing has been created
2020-07-19 07:23:05.305 INFO   : voco: Voco thing created
2020-07-19 07:23:05.309 INFO   : voco: available audio cards: ['ALSA', 'Connect']
2020-07-19 07:23:05.313 INFO   : voco: Possible audio capture devices: ['Attached device (1,0)']
2020-07-19 07:23:05.317 INFO   : voco: Snips has already been extracted
2020-07-19 07:23:05.322 INFO   : voco: -Debugging was in config
2020-07-19 07:23:05.325 INFO   : voco: Debugging enabled
2020-07-19 07:23:05.330 INFO   : voco: -Microphone is present in the config data: Attached device (1,0)
2020-07-19 07:23:05.334 INFO   : voco: --Using microphone from config
2020-07-19 07:23:05.338 INFO   : voco: -Speaker is present in the config data: Auto
2020-07-19 07:23:05.342 INFO   : voco: -Voice accent is present in the config data.
2020-07-19 07:23:05.347 INFO   : voco: -Voice pitch is present in the config data.
2020-07-19 07:23:05.354 INFO   : voco: -Voice speed is present in the config data.
2020-07-19 07:23:05.362 INFO   : voco: -Metric preference is present in the config data.
2020-07-19 07:23:05.368 INFO   : voco: -Authorization token is present in the config data.
2020-07-19 07:23:05.373 INFO   : voco: GET PATH = /things
2020-07-19 07:23:05.380 INFO   : voco: API GET: 200, OK
2020-07-19 07:23:05.386 INFO   : voco: self.server is now: http://127.0.0.1:8080
2020-07-19 07:23:05.395 INFO   : voco: Setting audio input to USB/Hat
2020-07-19 07:23:05.400 INFO   : voco: Setting audio output to automatically switch
2020-07-19 07:23:05.402 INFO   : voco: Error handling time zone calculation: 'CST'

**Comment by TobiBu** [comment] 2020-07-30 17:16
I updated voco as well and still can not make the feedback sound nor the speech work with a speaker attached to the audio jack. The debug output in the logs says several error messages:

> 2020-07-30 19:11:25.756 INFO   : voco: Alsa environment variable for speech output set to: ALSA
2020-07-30 19:11:25.758 INFO   : voco: nanotts_volume = 1.0
2020-07-30 19:11:25.759 INFO   : voco: Error speaking: Command '('/home/pi/.mozilla-iot/addons/voco/snips/nanotts', '-l', '/home/pi/.mozilla-iot/addons/voco/snips/lang', '-v', 'en-GB', '--volume', '1.0', '--speed', '0.9', '--pitch', '1.2', '-p')' died with <Signals.SIGABRT: 6>.
2020-07-30 19:11:25.760 INFO   : voco: MQTT msg.topic = hermes/hotword/toggleOn
2020-07-30 19:11:25.761 INFO   : voco: MQTT msg.topic = hermes/hotword/default/detected
2020-07-30 19:11:25.762 INFO   : voco: >> Hotword detected
2020-07-30 19:11:25.763 INFO   : voco: MQTT msg.topic = hermes/hotword/toggleOff
2020-07-30 19:11:25.764 INFO   : voco: MQTT msg.topic = hermes/intent/createcandle:set_state
2020-07-30 19:11:25.765 INFO   : voco: -----------------------------------
2020-07-30 19:11:25.766 INFO   : voco: >> Received intent message.
2020-07-30 19:11:25.826 INFO   : zigbee-adapter: setProperty property: on for: zb-7cb03eaa0a096efd-undefined profileId: 0104 endpoint: 3 clusterId: 0006 zcl: on value: true
2020-07-30 19:11:25.885 ERROR  : voco: Using Lingware directory: /home/pi/.mozilla-iot/addons/voco/snips/lang
2020-07-30 19:11:25.887 ERROR  : voco: error: opening pcm device failed No such file or directory
2020-07-30 19:11:25.888 ERROR  : voco: nanotts: pcm.c:736: snd_pcm_stream: Assertion `pcm' failed.
2020-07-30 19:11:28.189 ERROR  : voco: /home/pi/.mozilla-iot/addons/voco/sounds/start_of_input100.wav: No such file or directory

**Comment by createcandle** [comment] 2020-07-31 13:01
It's a strange case.

`voco: /home/pi/.mozilla-iot/addons/voco/sounds/start_of_input100.wav: No such file or directory`

I checked, and those files are definitely in the addon. You can check it yourself at https://wwww.candlesmarthome.com/assistant/voco-1.1.4.tgz

So I don't know what is going on if your system somehow doesn't have those files. Did you install Voco from Github perhaps?

I took an old Pi3 SD card which still had voco 1.1.0 on it, and updated it. It failed for a very strange reason: missing `audio_output` in the persistence file. Even though there was code to fix that eventuality. I've now added another layer of protection, and tested it. So that _should_ work in the new version 1.1.5.

`voco: Error speaking: Command '('/home/pi/.mozilla-iot/addons/voco/snips/nanotts', '-l', '/home/pi/.mozilla-iot/addons/voco/snips/lang', '-v', 'en-GB', '--volume', '1.0', '--speed', '0.9', '--pitch', '1.2', '-p')' died with <Signals.SIGABRT: 6>.`

That issue is quite strange. I can't reproduce it on my own Pi's. From some searching it could be related to low memory. Are you running a lot of heavy things?

To be sure:
- Voco has only been tested to work on Raspberry Pi 3B(+) and 4B
- It's designed for the disk image that Mozilla provides. Using other custom installations of Linux might not work.
- Voco should be installed via the Gateway addon system. Don't install it from Github manually, that's not guaranteed to work.

One way you might be able to solve these issues is to start from a clean Gateway disk image. Would you be willing to test that?

Also, please be very explicit about how your system is configured. What Raspberri pi is used, if there are customisations, etc. Without such details its very hard to remotely guess what could be going on.

**Comment by TobiBu** [comment] 2020-07-31 20:33
Hi,

Thanks for the quick answer. I used the official disk image on a Pi 4B and installed Voco via the Gateway. Long story short: I bought a new SD card today and started with a fresh install and it works all fine.

Not entirely sure what went wrong with the first install but what I noticed is: My first SD card was 32 GB in size, while the new is 64 GB. Not sure how large the speech recognition model of Voco is in size but could it be that for some reason 32 GB was not enough to fully unpack?

**Comment by flatsiedatsie** [comment] 2020-07-31 20:49
No that shouldn't be a problem. It's only 100mb. Great to hear it works now!

**Comment by createcandle** [comment] 2020-08-03 08:54
I was able to replicate the issue on a Raspberry Pi 3. I've created a fix. See https://github.com/mozilla-iot/addon-list/pull/981

**Comment by createcandle** [comment] 2020-08-14 21:39
@TobiBu Is the issue fixed for you now?

**Comment by TobiBu** [comment] 2020-08-16 18:56
Hi,

I downloaded a fresh version of the Gateway onto a new SD-card. After a fresh install everything worked. 
That said, I am not sure if its the fix or the fresh install.

Anyway, thanks for all your help!
Now Voco and the Gateway work fine for me.

**Comment by createcandle** [comment] 2020-08-16 19:04
Glad to hear it. I'll go ahead and close this issue.

**Closed as completed by createcandle** 2020-08-16 19:04 UTC

**Comment by flatsiedatsie** [comment] 2021-01-22 16:24
The latest version of Voco has a new audio samplerate feature which might help people with USB speakers.
